# -*- coding: utf-8 -*-
"""text classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVMYl6UpNsdJ-gclKRdCGBw_hYPZJXGv
"""

import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"E:\DataScience-data\bbc_news_mixed.csv")

df.shape

df.head()

df['label'].value_counts()

from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
df['label']=l1.fit_transform(df['label'])

df.head()

df['label'].value_counts()

for i in df.text[:2]:
    print(i)

from sklearn.feature_extraction.text import CountVectorizer
conv=CountVectorizer(stop_words='english')

sample_data=['This is smaple documents', 'This is second documents','This is my documents']

#c=CountVectorizer()

##xsample=c.fit_transform(sample_data)

#c.get_feature_names()

#print(xsample.toarray())

bow=conv.fit_transform(df.text)

bow.shape

len(conv.vocabulary_)

bow_df=pd.DataFrame.sparse.from_spmatrix(bow, columns=conv.get_feature_names(),
                                        index=df.index)

type(bow_df)

bow_df.head()

bow_df.iloc[:20,5000:5050]

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(bow,df.label,train_size=0.8)

print(xtrain[0].shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

from sklearn.neural_network import MLPClassifier
algo=MLPClassifier()
algo.fit(xtrain,ytrain)

from sklearn.metrics import accuracy_score,confusion_matrix

ypred=algo.predict(xtest)

accuracy_score(ytest,ypred)

confusion_matrix(ytest,ypred)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=4000,stop_words='english')
#tfidf=TfidfVectorizer(stop_words='english')

#print(xsample.toarray())

#xsample=tfidf.fit_transform(sample_data)

#xsample.shape

#print(xsample.toarray())

#tfidf.get_feature_names()

"""![TF_IDF_1.png](attachment:TF_IDF_1.png)

![TF-IDF.png](attachment:TF-IDF.png)
"""

#tfidf=TfidfVectorizer(max_features=4000,stop_words='english')
newdata=tfidf.fit_transform(df.text)

xtrain,xtest,ytrain,ytest=train_test_split(newdata,df.label,train_size=0.8)

print(xtrain.shape)

algo.fit(xtrain,ytrain)
ypred=algo.predict(xtest)
accuracy_score(ytest,ypred)

newdata=["""The CSK squad have been in quarantine over the last week until it emerged yesterday that they would continue to remain so after a few members from the team had tested positive for COVID-19.

It is a significant blow for CSK, the three-time IPL champions. Raina is the team's leading run-getter, aggregating 4527 runs from 164 IPL games for the franchise. The No.3 batsman featured in 158 consecutive games for CSK (IPL + CPL) before missing his first game in the 2018 season with a calf injury.

Raina is also the second-highest scorer in IPL history with 5368 runs, only behind Virat Kohli's tally of 5412, and has taken the most catches (102) in the tournament history."""]

ndata=conv.transform(mydata)

ndata.shape

algo.predict(ndata)

mydata=["""Coca-Cola is offering voluntary buyouts to about 4,000 people to reduce the number of layoffs it says will take place as it streamlines operations.

Coca-Cola is reducing the number of its individual business segments from 17 to nine, which it said Friday will result in “voluntary and involuntary” staff cuts.

The streamlining is taking place during a rough stretch for Coca-Cola and almost all companies that cater to social events.

Half of Coca-Cola’s sales come from stadiums, movie theaters and other places where people gather in large numbers — venues that have been closed during the coronavirus pandemic. Revenue tumbled 28% in the Atlanta company's most recent quarter."""]

